@LearningAPI_HostAddress = https://localhost:7004
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJaaXYgT2giLCJlbWFpbCI6Inppdm9oMDdAZ21haWwuY29tIiwibmJmIjoxNzY3NDQwODk2LCJleHAiOjE3NzAwMzI4OTYsImlhdCI6MTc2NzQ0MDg5Nn0.Jzf03NdC_X8w1b9AviO8acy1oZTzjMSKM4cBg96z0e0

GET {{LearningAPI_HostAddress}}/tutorial?search=

###

POST {{LearningAPI_HostAddress}}/tutorial
Content-Type: application/json
Authorization: Bearer {{token}}

{
 "title": "My tutorial",
 "description": "by Haiyun"
}

###

GET {{LearningAPI_HostAddress}}/tutorial/1

###

PUT {{LearningAPI_HostAddress}}/tutorial/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
 "title": "My Story",
 "description": "Your Song ❤"
}

###

DELETE {{LearningAPI_HostAddress}}/tutorial/3
Authorization: Bearer {{token}}

###

POST {{LearningAPI_HostAddress}}/user/register
Content-Type: application/json

{
 "name": "Ziv Oh",
 "email": "zivoh07@gmail.com",
 "password": "ZivOh123!"
}

###

POST {{LearningAPI_HostAddress}}/user/login
Content-Type: application/json

{
 "email": "ZivOh07@gmail.com",
 "password": "ZivOh123!"
}


###

GET {{LearningAPI_HostAddress}}/user/auth
Authorization: Bearer {{token}}

###




// Inventory
POST {{LearningAPI_HostAddress}}/inventory
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ProductId": 4,
  "Quantity": 95,
  "LocationId": 1,
  "ExpiryDate": "2025-01-14T00:00:00"
}


###

GET {{LearningAPI_HostAddress}}/inventory?search=
Authorization: Bearer {{$bearerToken}}

###

@InventoryId=9
GET {{LearningAPI_HostAddress}}/inventory/{{InventoryId}}
Authorization: Bearer {{$bearerToken}}


###

PUT {{LearningAPI_HostAddress}}/inventory/{{InventoryId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ProductId": 4,
  "Quantity": 60,
  "LocationId": 1,
  "ExpiryDate": "2026-01-06T00:00:00"
}

###

DELETE {{LearningAPI_HostAddress}}/inventory/{{InventoryId}}
Authorization: Bearer {{token}}

###
